name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    if: contains('["onuratakan"]', github.actor)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"          

      - name: Run Version Bump Script
        run: python bump.py ${{ github.event.inputs.release_type }}


